### ISSUE TITLE
Find out more about the August 2008 meeting

### ISSUE THREAD

**Issue by h-lame** [lrug/lrug.org#22]
There's no record of it on the site, but it appears to have happened according to https://skillsmatter.com/meetups/167-lrug-meeting-august - maybe there's something in the mailing list archives and we can resurrect it from there.

**Comment by tomstuart** [comment]
The August (ditto September) 2008 meeting was [organised by @tomafro](http://lists.lrug.org/pipermail/chat-lrug.org/2008-July/002747.html), which may be why there isn’t anything on the site about it.

There was one talk [from @pat about Sphinx](http://lists.lrug.org/pipermail/chat-lrug.org/2008-August/002834.html), and another [from Aidy Lewis about Ruby/Watir](http://lists.lrug.org/pipermail/chat-lrug.org/2008-August/002844.html).

**Comment by h-lame** [comment]
Turns out that Pat [didn't actually talk at that meeting](http://lists.lrug.org/pipermail/chat-lrug.org/2008-August/002849.html) - which explains the meeting page on SM only have Aidy's talk.
