### ISSUE TITLE
Add README, CONTRIBUTING, etc...

### ISSUE THREAD

**Issue by h-lame** [lrug/lrug.org#23]
To help with letting people know what this repo is about and what we use it for.

**Comment by dotemacs** [comment]
Hi @h-lame 

here is the [README](https://gist.github.com/dotemacs/30977e83f7ecea4a53f7)
and [CONTRIBUTING](https://gist.github.com/dotemacs/cbcb080671483078468f)

**Comment by h-lame** [comment]
Thanks @dotemacs!
