### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by h-lame** [lrug/lrug.org#55]
Reminder to investigate dreamhost's letsencrypt integration (https://www.dreamhost.com/hosting/ssl-tls-certificates/) and get lrug.org onto https.

**Comment by MikeRogers0** [comment]
I _really_ want to see SSL on http://lrug.org - From what I gather it helps a lot with search ranking.

I see the options of resolving this as:

1. Setup SSL on Dreamhost (Are we still on Dreamhost?)
2. Move to GitHub Pages
3. Switch to https://www.netlify.com - I've used this a bunch ( I also setup https://github.com/Ruby-Starter-Kits/Docker-Middleman-Template if you want to see some quick start code), the big advantage is it allows for preview environments for PRs which is super nice.

**Comment by h-lame** [comment]
Hey @MikeRogers0 - turns out the Dreamhost lets encrypt integration is super simple, so we've pressed the button and now we have https://lrug.org and it does an automatic redirect from http -> https (although your browser may decide otherwise because it's hsts and you may have a cache).  We need to update the references to http://assets.lrug.org to go to https://assets otherwise we get mixed content warnings, but we're on it as it should be a quick find-and-replace.

We never bothered before because it's just a static site, there's no real need for it to have ssl, but if google is gonna penalise us in terms of site rankings then I guess that's a good enough reason.  Luckily it was super easy to do.

Thanks for prompting us to look at this in more detail!

**Comment by MikeRogers0** [comment]
@h-lame Any thoughts on Netlify for their preview app capabilities? Or would that be overkill?

**Comment by h-lame** [comment]
Reckon it'd be overkill.  We have https://new.lrug.org (which is currently manually deployed) for previews if we need them, but so far, the changes to the site have been fairly minimal so previews not really needed.

**Comment by h-lame** [comment]
Closed by https://github.com/lrug/lrug.org/commit/8c2cad742c4f487d1aa165b5933cf962ec442438 (and some clicking around in the dreamhost admin panel to enable their auto-renewing letsencrypt stuff).
