### ISSUE TITLE
Collect coverage links from lanyrd

### ISSUE THREAD

**Issue by h-lame** [lrug/lrug.org#61]
Looks like lanyrd is being left to die which is a shame for many reasons.  The biggest shame for us is that since 2011 we've used Lanyrd to collect a load of links to videos, slides, write-ups, and relevant git repos. If lanyrd goes away we lose these links.

It's a bit weird to use lanyrd for this anyway, as the canonical artefact for a meeting should probably be the lrug.org page for it.  We should:
1. scrape the coverage links from lanyrd while it's still up (is there an API?) so we don't lose them
2. work out some way of attaching them programatically to the meeting pages
3. do any digging neccessary to backfill links for meetings before we used lanyrd

**Comment by tomstuart** [comment]
https://github.com/andrew/lanyrd worked last time I tried it, although I can’t check it now because Lanyrd is down.

**Comment by tomstuart** [comment]
Surprisingly, it does still work.

**Comment by h-lame** [comment]
There doesn't seem to be an API method or object response that includes coverage though, so it'll have to be scraped :(  Annoyingly, `http://lanyrd.com/<year>/<event-slug>/coverage` doesn't seem to always include all coverage for an event, may have to scrape each session.  (See http://lanyrd.com/2016/lrug-august/coverage/ vs. http://lanyrd.com/2016/lrug-september/coverage/ vs. http://lanyrd.com/2016/lrug-september/sfdwcc/ )

**Comment by h-lame** [comment]
This probably fixed by #91 TBH.

**Comment by h-lame** [comment]
Think we can close this as #91 is our best bet.  There are more places we should scour for coverage links, but that can live in a new issue IMHO.
