### ISSUE TITLE
Upgrade middleman + dependencies

### ISSUE THREAD

**Issue by h-lame** [lrug/lrug.org#64]
Middleman 4 is out (since Dec 2015 no less) so we should consider upgrading.  We don't use a lot of other dependencies but it'd be a chance to bump our version of ruby and such too.  When building the writing was on the wall about the changes coming in middleman 4 so we tried to not use anything we knew was going away.  Handily, there's a guide to help us: https://middlemanapp.com/basics/upgrade-v4/

**Comment by greysteil** [comment]
I'm up for doing this. Would you guys be up for using [Dependabot](https://dependabot.com) to stay up-to-date once I do?

**Comment by h-lame** [comment]
This is obviously a never ending requirement, but we _are_ on v4 of middleman now (see #80) which was the major reason for opening this issue in the first place, so I think it makes sense to close this for now.

**Comment by greysteil** [comment]
No worries. Dependabot got acquired by GitHub 6 months ago, and I gave a talk about it at LRUG a year ago, so much has changed since 2017!
