### ISSUE TITLE
Typo on Pauls Feb 2017 talk description

### ISSUE THREAD

**Issue by Najaf** [lrug/lrug.org#66]
Here: lrug.org/source/meetings/2017/february/index.html.md

In Paul's talk description:

If you've done much programming, you've probably worked with binary, hexadecimal, and perhaps octal in addition to normal decimal numbers. But what about base three? And what about **~~bass~~** base three with a twist, where each digit can be positive or negative? Why would you even want to do that? It really exists, it's called Balanced Ternary, and it has some interesting properties.

Unless it's deliberate and part of the talk?

@h-lame

**Comment by h-lame** [comment]
I imagine it's not deliberate, no.  Thanks for spotting.

**Comment by h-lame** [comment]
Fixed in faa90a8b58133188f85d61b7af62a00a8955bbc3
